# This file based on https://gist.github.com/mwouts/9842452d020c08faf9e84a3bba38a66f
# See: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
# 2022-08-06 - slg - Updated os to be 'macos-latest', 'ubuntu-20.04', 'ubuntu-22.04'
#                    See https://github.com/actions/virtual-environments for details.
# 2020-06-22 - slg - customized
# 2020-06-27 - slg - expanded to G++ for MacOS
# 2020-07-03 - slg - ported to be13_api; removed python (be13_api doesn't use python)
# 2021-05-07 - slg - Started work again
# 2022-02-10 - slg - renamed be20_api. Our work here is done.

name: BE2 Unit Tests on MacOS and Ubuntu (c++17)

on:
  push:
    branches:
      - '**' # This will trigger the action for all branches
  pull_request:
    branches:
      - main # Specify the branches for which pull_request events should trigger the action

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04]
        platform: [x64, arm64]
    runs-on: ${{ matrix.os }}

    env:
      DEBUG_5G: FALSE
      DEBUG_FAST: TRUE
      MAKE_OPTS: -j2

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

    - name: Extract Version from configure.ac
      id: extract_version
      run: |
        VERSION=$(grep 'AC_INIT' configure.ac | sed -n 's/.*AC_INIT.*\[\(.*\)\], \[\(.*\)\].*/\2/p')
        echo "Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
