# This file based on https://gist.github.com/mwouts/9842452d020c08faf9e84a3bba38a66f
# See: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
# 2020-06-22 - slg - customized
# 2020-06-27 - slg - expanded to G++ for MacOS
# 2020-07-03 - slg - ported to be13_api; removed python (be13_api doesn't use python)
# 2021-05-07 - slg - Started work again

name: BE2 CI (c++17)
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-10.15']
        #os: ['macos-10.15', 'ubuntu-18.04']

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install C++ dependencies on MacOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install autoconf automake libtool


      - name: Install C++ dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
           sudo apt install -y libtool autoconf automake libssl-dev pkg-config

      - name: Update autoconf
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          wget https://ftpmirror.gnu.org/autoconf/autoconf-2.71.tar.gz
          tar xfz autoconf-2.71.tar.gz && cd autoconf-2.71 && ./configure && make && sudo make install

      - name: c/c++ compile test
        run: |
          autoconf --version
          automake --version
          bash bootstrap.sh && ./configure
          make check  || (cat src/Makefile ; for fn in test*.log ; do echo ""; echo $fn ; cat $fn ; done; exit 1)
          make distclean && ./configure && make distcheck

      - uses: ammaraskar/gcc-problem-matcher@0.1
        name: GCC Problem Matcher

      - name: codecov report
        if: startsWith(matrix.os, 'ubuntu')
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
           bash .make-codecov

#      - name: regresion test
#        run: |
#          cd tests
#          python3 regress.py --datacheck
