name: Create tarball including submodules

on: [workflow_dispatch]

permissions:
  actions: read
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and init submodules recursively
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Extract Version from configure.ac
      id: extract_version
      run: |
        VERSION=$(grep 'AC_INIT' configure.ac | sed -n 's/.*AC_INIT.*\[\(.*\)\], \[\(.*\)\].*/\2/p')
        echo "Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Setup
      run: |
        chmod +x etc/install_autotools.sh
        bash ./etc/install_autotools.sh
        chmod +x && bootstrap.sh
        ./bootstrap.sh
        ./configure -q

    - name: Create release tarball
      run: |
        make dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: bulk_extractor-${VERSION}.tar.gz
        path: bulk_extractor-${VERSION}.tar.gz

    - name: Upload binaries to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bulk_extractor-${VERSION}.tar.gz
        asset_name: bulk_extractor-${VERSION}.tar.gz
        asset_content_type: application/gzip
